/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as SolutionsWebPlatformsDashboardsRouteImport } from './routes/solutions/web-platforms-dashboards'
import { Route as SolutionsUiUxDesignRouteImport } from './routes/solutions/ui-ux-design'
import { Route as SolutionsSaasProductEngineeringRouteImport } from './routes/solutions/saas-product-engineering'
import { Route as SolutionsMobileAppDevelopmentRouteImport } from './routes/solutions/mobile-app-development'
import { Route as SolutionsFintechPaymentSystemsRouteImport } from './routes/solutions/fintech-payment-systems'
import { Route as SolutionsEnterpriseWorkflowAutomationRouteImport } from './routes/solutions/enterprise-workflow-automation'
import { Route as SolutionsAiPoweredPlatformsRouteImport } from './routes/solutions/ai-powered-platforms'
import { Route as SolutionsSlugRouteImport } from './routes/solutions.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/solutions/',
  path: '/solutions/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsWebPlatformsDashboardsRoute =
  SolutionsWebPlatformsDashboardsRouteImport.update({
    id: '/solutions/web-platforms-dashboards',
    path: '/solutions/web-platforms-dashboards',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsUiUxDesignRoute = SolutionsUiUxDesignRouteImport.update({
  id: '/solutions/ui-ux-design',
  path: '/solutions/ui-ux-design',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsSaasProductEngineeringRoute =
  SolutionsSaasProductEngineeringRouteImport.update({
    id: '/solutions/saas-product-engineering',
    path: '/solutions/saas-product-engineering',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsMobileAppDevelopmentRoute =
  SolutionsMobileAppDevelopmentRouteImport.update({
    id: '/solutions/mobile-app-development',
    path: '/solutions/mobile-app-development',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsFintechPaymentSystemsRoute =
  SolutionsFintechPaymentSystemsRouteImport.update({
    id: '/solutions/fintech-payment-systems',
    path: '/solutions/fintech-payment-systems',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsEnterpriseWorkflowAutomationRoute =
  SolutionsEnterpriseWorkflowAutomationRouteImport.update({
    id: '/solutions/enterprise-workflow-automation',
    path: '/solutions/enterprise-workflow-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsAiPoweredPlatformsRoute =
  SolutionsAiPoweredPlatformsRouteImport.update({
    id: '/solutions/ai-powered-platforms',
    path: '/solutions/ai-powered-platforms',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsSlugRoute = SolutionsSlugRouteImport.update({
  id: '/solutions/$slug',
  path: '/solutions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => IndustriesRoute,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/ai-powered-platforms': typeof SolutionsAiPoweredPlatformsRoute
  '/solutions/enterprise-workflow-automation': typeof SolutionsEnterpriseWorkflowAutomationRoute
  '/solutions/fintech-payment-systems': typeof SolutionsFintechPaymentSystemsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/saas-product-engineering': typeof SolutionsSaasProductEngineeringRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/web-platforms-dashboards': typeof SolutionsWebPlatformsDashboardsRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/ai-powered-platforms': typeof SolutionsAiPoweredPlatformsRoute
  '/solutions/enterprise-workflow-automation': typeof SolutionsEnterpriseWorkflowAutomationRoute
  '/solutions/fintech-payment-systems': typeof SolutionsFintechPaymentSystemsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/saas-product-engineering': typeof SolutionsSaasProductEngineeringRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/web-platforms-dashboards': typeof SolutionsWebPlatformsDashboardsRoute
  '/solutions': typeof SolutionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/industries': typeof IndustriesRouteWithChildren
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/solutions/$slug': typeof SolutionsSlugRoute
  '/solutions/ai-powered-platforms': typeof SolutionsAiPoweredPlatformsRoute
  '/solutions/enterprise-workflow-automation': typeof SolutionsEnterpriseWorkflowAutomationRoute
  '/solutions/fintech-payment-systems': typeof SolutionsFintechPaymentSystemsRoute
  '/solutions/mobile-app-development': typeof SolutionsMobileAppDevelopmentRoute
  '/solutions/saas-product-engineering': typeof SolutionsSaasProductEngineeringRoute
  '/solutions/ui-ux-design': typeof SolutionsUiUxDesignRoute
  '/solutions/web-platforms-dashboards': typeof SolutionsWebPlatformsDashboardsRoute
  '/solutions/': typeof SolutionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/solutions/$slug'
    | '/solutions/ai-powered-platforms'
    | '/solutions/enterprise-workflow-automation'
    | '/solutions/fintech-payment-systems'
    | '/solutions/mobile-app-development'
    | '/solutions/saas-product-engineering'
    | '/solutions/ui-ux-design'
    | '/solutions/web-platforms-dashboards'
    | '/solutions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/solutions/$slug'
    | '/solutions/ai-powered-platforms'
    | '/solutions/enterprise-workflow-automation'
    | '/solutions/fintech-payment-systems'
    | '/solutions/mobile-app-development'
    | '/solutions/saas-product-engineering'
    | '/solutions/ui-ux-design'
    | '/solutions/web-platforms-dashboards'
    | '/solutions'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/industries'
    | '/partners'
    | '/privacy'
    | '/terms'
    | '/blog/$slug'
    | '/case-studies/$slug'
    | '/industries/$slug'
    | '/solutions/$slug'
    | '/solutions/ai-powered-platforms'
    | '/solutions/enterprise-workflow-automation'
    | '/solutions/fintech-payment-systems'
    | '/solutions/mobile-app-development'
    | '/solutions/saas-product-engineering'
    | '/solutions/ui-ux-design'
    | '/solutions/web-platforms-dashboards'
    | '/solutions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  IndustriesRoute: typeof IndustriesRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  SolutionsSlugRoute: typeof SolutionsSlugRoute
  SolutionsAiPoweredPlatformsRoute: typeof SolutionsAiPoweredPlatformsRoute
  SolutionsEnterpriseWorkflowAutomationRoute: typeof SolutionsEnterpriseWorkflowAutomationRoute
  SolutionsFintechPaymentSystemsRoute: typeof SolutionsFintechPaymentSystemsRoute
  SolutionsMobileAppDevelopmentRoute: typeof SolutionsMobileAppDevelopmentRoute
  SolutionsSaasProductEngineeringRoute: typeof SolutionsSaasProductEngineeringRoute
  SolutionsUiUxDesignRoute: typeof SolutionsUiUxDesignRoute
  SolutionsWebPlatformsDashboardsRoute: typeof SolutionsWebPlatformsDashboardsRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/solutions'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/web-platforms-dashboards': {
      id: '/solutions/web-platforms-dashboards'
      path: '/solutions/web-platforms-dashboards'
      fullPath: '/solutions/web-platforms-dashboards'
      preLoaderRoute: typeof SolutionsWebPlatformsDashboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ui-ux-design': {
      id: '/solutions/ui-ux-design'
      path: '/solutions/ui-ux-design'
      fullPath: '/solutions/ui-ux-design'
      preLoaderRoute: typeof SolutionsUiUxDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/saas-product-engineering': {
      id: '/solutions/saas-product-engineering'
      path: '/solutions/saas-product-engineering'
      fullPath: '/solutions/saas-product-engineering'
      preLoaderRoute: typeof SolutionsSaasProductEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/mobile-app-development': {
      id: '/solutions/mobile-app-development'
      path: '/solutions/mobile-app-development'
      fullPath: '/solutions/mobile-app-development'
      preLoaderRoute: typeof SolutionsMobileAppDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/fintech-payment-systems': {
      id: '/solutions/fintech-payment-systems'
      path: '/solutions/fintech-payment-systems'
      fullPath: '/solutions/fintech-payment-systems'
      preLoaderRoute: typeof SolutionsFintechPaymentSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/enterprise-workflow-automation': {
      id: '/solutions/enterprise-workflow-automation'
      path: '/solutions/enterprise-workflow-automation'
      fullPath: '/solutions/enterprise-workflow-automation'
      preLoaderRoute: typeof SolutionsEnterpriseWorkflowAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/ai-powered-platforms': {
      id: '/solutions/ai-powered-platforms'
      path: '/solutions/ai-powered-platforms'
      fullPath: '/solutions/ai-powered-platforms'
      preLoaderRoute: typeof SolutionsAiPoweredPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/$slug': {
      id: '/solutions/$slug'
      path: '/solutions/$slug'
      fullPath: '/solutions/$slug'
      preLoaderRoute: typeof SolutionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof IndustriesRoute
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface IndustriesRouteChildren {
  IndustriesSlugRoute: typeof IndustriesSlugRoute
}

const IndustriesRouteChildren: IndustriesRouteChildren = {
  IndustriesSlugRoute: IndustriesSlugRoute,
}

const IndustriesRouteWithChildren = IndustriesRoute._addFileChildren(
  IndustriesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  IndustriesRoute: IndustriesRouteWithChildren,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  SolutionsSlugRoute: SolutionsSlugRoute,
  SolutionsAiPoweredPlatformsRoute: SolutionsAiPoweredPlatformsRoute,
  SolutionsEnterpriseWorkflowAutomationRoute:
    SolutionsEnterpriseWorkflowAutomationRoute,
  SolutionsFintechPaymentSystemsRoute: SolutionsFintechPaymentSystemsRoute,
  SolutionsMobileAppDevelopmentRoute: SolutionsMobileAppDevelopmentRoute,
  SolutionsSaasProductEngineeringRoute: SolutionsSaasProductEngineeringRoute,
  SolutionsUiUxDesignRoute: SolutionsUiUxDesignRoute,
  SolutionsWebPlatformsDashboardsRoute: SolutionsWebPlatformsDashboardsRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
